site: Daniel Neves
url: http://danielneves.com
title: Asko
description: espaço para me conhecer e ver meu trbaalho
googlewebfonts: Fira+Code:wght@400;500;700
# twitter:
#   username: #danielneves
#   card: summary
#   creator: #yourusername
author:
  # twitter: #yourusername
  name: @danielneves
  avatar:
  email: contato@danielneves.com
  url: http://danielneves.com
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"