# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: pt-BR

# Site title
title: "Daniel Neves | Product Designer"

# A description of your site for meta tag, search engine results.
description: "Product Designer, UX Designer, ilustrador e artista visual"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-VJ8EPY4MF8"

# Site navigation - each item must have a title and a url.
navigation:
  # - text: Home
  #   url: /
  - text: Contato
    url: /contato
#  - text: Portfolio(pdf)
#    url: /files/Daniel_Neves_Portfolio.pdf
  # - text: Currículo(pdf)
  #   url: /files/Daniel_Neves_CV.pdf

# # The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#1169FF'

# Site footer
footer:
  content: "contato@danielneves.com"
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# # Conversion
# markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
